name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: 1.12.0.1517
          bb: 1.12.197

      - uses: actions/cache@v4
        with:
          path:
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - run: bb test
